version: '2'

services:
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    image: nginx-custom
    ports:
      - "80:80"
  proxy:
    build:
      context: .
      dockerfile: proxy.Dockerfile
    image: nginx-proxy-custom
    ports:
      - "8090:8090"
  rabbit:
    build:
      context: .
      dockerfile: rabbit.Dockerfile
    image: test-rabbit
    expose:
      - "5672"
      - "15672"
      - "15674"
